// Generated by Selenium IDE - Modificado
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.time.Duration;
import java.util.*;

public class LoginincorrectoTest {
  private WebDriver driver;
  private Map<String, Object> vars;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void loginincorrecto() {
    driver.get("https://buggy.justtestit.org/");
    driver.manage().window().setSize(new Dimension(1239, 797));

    driver.findElement(By.name("login")).click();
    driver.findElement(By.name("login")).sendKeys("usuario_falso");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("12345");
    driver.findElement(By.cssSelector(".btn-success")).click();

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    WebElement mensajeError = wait.until(
        ExpectedConditions.visibilityOfElementLocated(
            By.xpath("//div[contains(text(),'Invalid username/password')]")
        )
    );

    assertTrue("El mensaje de error no se mostró correctamente.", mensajeError.isDisplayed());
  }
}